### ISSUE TITLE
Mainnet not in npm

### ISSUE THREAD

**Issue by zquestz** [HandCash/handcash-javascript#3]
Please add version 0.0.3 to npm. Seems it hasn't been pushed yet. =)

**Comment by rafa-js** [comment]
Ups, true! 
@cgcardona could you handle this? :)

**Comment by cgcardona** [comment]
Yup. On it now.

**Comment by rafa-js** [comment]
@GitCash send 50000 satoshi to @zquestz

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/137/image.png)](https://gitcash.io/claim/zquestz)
@zquestz

**Comment by rafa-js** [comment]
Thanks Gabriel!
@GitCash send 75000 satoshi to @cgcardona

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/138/image.png)](https://gitcash.io/claim/cgcardona)
@cgcardona

**Comment by cgcardona** [comment]
handcash v0.0.3 is live on npm. https://www.npmjs.com/package/handcash
